#!/usr/bin/env node
'use strict';
let cron = require('node-cron');
let arg_option = require('./src/execute/ArgOption');
let Executor = require('./src/execute/Executor');
let Constant = require('./src/execute/Constant');
let Context = require('./src/common/Context');

// connect mongo db
let ConnectMongo = require('./src/common/ConnectMongo');
let config = require('config');

Context.set(Constant.MONGO_EXPORT_CONTENTPOOL, ConnectMongo(config.get(Constant.MONGO_EXPORT_CONTENTPOOL)));
Context.set(Constant.MONGO_EXPORT_RAW, ConnectMongo(config.get(Constant.MONGO_EXPORT_RAW)));
Context.set(Constant.MONGO_IMPORT, ConnectMongo(config.get(Constant.MONGO_IMPORT)));
Context.set(Constant.ES_EXPORT, ConnectMongo(config.get(Constant.ES_EXPORT)));
Context.set(Constant.ES_IMPORT, config.get(Constant.ES_IMPORT));

let argv = require('yargs')
    .option('t', arg_option.type)
    .option('d', arg_option.data)
    .option('h', arg_option.hours)
    .option('r', arg_option.range)
    .option('i', arg_option.import)
    .option('c', arg_option.cron)
    .usage('Usage: run [options]')
    .example('run -t feed -d project -h 48 -r 500 -i mongo',
        `exporting rss's projects before 48 hours and one time export 500 projects.`)
    .help('help')
    .argv;

let options = {
    type: argv.type,
    data: argv.data,
    hours: argv.hours,
    range: argv.range
};
let _import = argv.import;
let _cron = argv.cron;

let shell = require('shelljs/global');
echo(`run --options ${JSON.stringify(options)} --import ${_import} --cron ${_cron}`);

let executor = new Executor(options);
let run = ()=> {
    if (!_import) {
        executor.import2Mongo();
        executor.import2ES();
    }
    if (_import === Constant.IMPORT_MONGO) executor.import2Mongo();
    if (_import === Constant.IMPORT_ES) executor.import2ES();
};

if (_cron) {
    cron.schedule(_cron, ()=>{
        echo(`cron: ${_cron}`);
        run();
    });
} else {
    run();
}

